version: "3"
services:
  postgres:
    container_name: postgres1
    build:
      context: postgres
      dockerfile: ./Dockerfile
    image: "simplon/postgres:0.0.1"
    restart: always
    environment:
      POSTGRES_DB: simplon
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 2zerezGZEGZ55??
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/db.sql
      # - ./postgres/db/init.sh:/docker-entrypoint-initdb.d/init1.sh
    ports:
      - "0.0.0.0:5454:5432"
    networks:
      - simplon-net
  node-api:
    container_name: "node-api"
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    command: npm start
    restart: always
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - postgres
    networks:
      - simplon-net   
networks:
  simplon-net: