-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    email character varying NOT NULL,
    pseudo character varying NOT NULL,
    user_id serial NOT NULL,
    password_users character varying NOT NULL,
    is_admin boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.courses
(
    desciption text NOT NULL,
    title character varying NOT NULL,
    course_id serial NOT NULL,
    note int4range NOT NULL,
    fk_user_id integer,
    PRIMARY KEY (course_id)
);

CREATE TABLE IF NOT EXISTS public.courses_step
(
    desciption text NOT NULL,
    title character varying NOT NULL,
    coursesstep_id serial NOT NULL,
    fk_course_id integer,
    PRIMARY KEY (coursesstep_id)
);

CREATE TABLE IF NOT EXISTS public.courses_comments
(
    message_course text NOT NULL,
    date_course date NOT NULL,
    comment_id serial NOT NULL,
    fk_user_id integer,
    fk_course_id integer,
    PRIMARY KEY (comment_id)
);

ALTER TABLE public.courses_comments
    ADD FOREIGN KEY (fk_user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.courses_comments
    ADD FOREIGN KEY (fk_course_id)
    REFERENCES public.courses (course_id)
    NOT VALID;


ALTER TABLE public.courses
    ADD FOREIGN KEY (fk_user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.courses_step
    ADD FOREIGN KEY (fk_course_id)
    REFERENCES public.courses (course_id)
    NOT VALID;

INSERT INTO users (email, pseudo, password_users, is_admin)
VALUES('f.elaya@live.fr','delpiero', 'pwd', TRUE);
END;

